// Demo data for when Supabase is not configured

// Check if we're in demo mode
export const isDemo = () => {
  return !process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
}

export const demoMembers = [
  {
    id: "demo-member-1",
    member_code: "VIP123456ABCD",
    qr_code: "/placeholder.svg?height=256&width=256&text=QR-VIP123456ABCD",
    full_name: "Juan Pérez",
    email: "juan.perez@email.com",
    phone: "+1234567890",
    membership_start: "2024-01-01",
    membership_end: "2024-04-01",
    is_active: true,
    total_spent: 1250.5,
    loyalty_points: 125,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "demo-member-2",
    member_code: "VIP789012EFGH",
    qr_code: "/placeholder.svg?height=256&width=256&text=QR-VIP789012EFGH",
    full_name: "María García",
    email: "maria.garcia@email.com",
    phone: "+1234567891",
    membership_start: "2024-02-01",
    membership_end: "2024-05-01",
    is_active: true,
    total_spent: 890.25,
    loyalty_points: 89,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "demo-member-3",
    member_code: "VIP345678IJKL",
    qr_code: "/placeholder.svg?height=256&width=256&text=QR-VIP345678IJKL",
    full_name: "Carlos López",
    email: "carlos.lopez@email.com",
    phone: "+1234567892",
    membership_start: "2023-12-01",
    membership_end: "2024-03-01",
    is_active: false,
    total_spent: 2100.75,
    loyalty_points: 210,
    created_at: "2023-12-01T00:00:00Z",
  },
]

export const demoProducts = [
  {
    id: "prod-1",
    name: "Whisky Premium",
    description: "Whisky de 18 años",
    price: 150.0,
    cost_price: 75.0,
    category: "Bebidas Premium",
    loyalty_points_earned: 15,
    points_per_dollar: 0.1,
    product_qr_code: "PRD123456",
    stock_quantity: 25,
    min_stock_alert: 5,
    is_active: true,
    is_featured: true,
    preparation_time: 2,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-2",
    name: "Cocktail Signature",
    description: "Cocktail exclusivo de la casa",
    price: 80.0,
    cost_price: 32.0,
    category: "Bebidas Premium",
    loyalty_points_earned: 8,
    points_per_dollar: 0.1,
    product_qr_code: "PRD789012",
    stock_quantity: 50,
    min_stock_alert: 10,
    is_active: true,
    is_featured: false,
    preparation_time: 5,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-3",
    name: "Tabla de Quesos Gourmet",
    description: "Selección de quesos importados",
    price: 120.0,
    cost_price: 48.0,
    category: "Aperitivos Gourmet",
    loyalty_points_earned: 12,
    points_per_dollar: 0.1,
    product_qr_code: "PRD345678",
    stock_quantity: 15,
    min_stock_alert: 5,
    is_active: true,
    is_featured: true,
    preparation_time: 8,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-4",
    name: "Gin Tonic Premium",
    description: "Gin importado con tónica artesanal",
    price: 95.0,
    cost_price: 45.0,
    category: "Bebidas Premium",
    loyalty_points_earned: 10,
    points_per_dollar: 0.1,
    product_qr_code: "PRD901234",
    stock_quantity: 30,
    min_stock_alert: 8,
    is_active: true,
    is_featured: true,
    preparation_time: 3,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-5",
    name: "Mojito Clásico",
    description: "Ron blanco, menta fresca y lima",
    price: 70.0,
    cost_price: 28.0,
    category: "Bebidas Premium",
    loyalty_points_earned: 7,
    points_per_dollar: 0.1,
    product_qr_code: "PRD567890",
    stock_quantity: 40,
    min_stock_alert: 10,
    is_active: true,
    is_featured: false,
    preparation_time: 4,
    created_at: "2024-01-01T00:00:00Z",
  },
]

export const demoStats = {
  totalMembers: 3,
  activeMembers: 2,
  expiringMembers: 1,
  todayRevenue: 450.0,
  monthlyRevenue: 12500.0,
  totalTransactions: 156,
  pendingRewards: 5,
}

export const demoNotifications = [
  {
    id: "notif-1",
    member_id: "demo-member-1",
    notification_type: "expiring_soon",
    message: "La membresía de Juan Pérez expira en 5 días",
    is_read: false,
    created_at: "2024-01-10T00:00:00Z",
  },
]

export const demoTransactions = [
  {
    id: "trans-1",
    transaction_code: "TXN001",
    member_id: "demo-member-1",
    total_amount: 150.0,
    payment_method: "card",
    payment_status: "completed",
    loyalty_points_earned: 15,
    created_at: "2024-01-10T18:30:00Z",
  },
  {
    id: "trans-2",
    transaction_code: "TXN002",
    member_id: "demo-member-2",
    total_amount: 89.5,
    payment_method: "digital",
    payment_status: "completed",
    loyalty_points_earned: 9,
    created_at: "2024-01-10T19:15:00Z",
  },
]
